Add SA1031
dominikh/go-tools pull request #1424
Opened 2023-07-11 22:11 UTC by echlebek

This commit adds SA1031, a check that detects trivially overlapping slices passed to encoders. Currently, encoding/ascii85, encoding/base32, encoding/base64, and encoding/hex are supported. The check will also check if constant nil is passed to dst, when src is non-nil.

There is currently no Phi or Sigma analysis done. I need to come up with test cases for these situations before adding support for them.

Closes: gh-1391

2023-07-11 22:13 UTC, echlebek commented
A note, I decided to avoid flagging when dst is nil. It isn't really related to the intent of the check, an unlikely mistake to make, and trivial to find if it is made. Need to rewrite the commit message in light of that.

2023-09-21 10:59 UTC, dominikh requested changes

2023-09-21 10:59 UTC, dominikh commented on staticcheck/doc.go
> +		Since:    "2023.2",
This should say "Unreleased" until we actually make a new release.

2023-09-21 10:59 UTC, dominikh commented on staticcheck/doc.go
> +		Text:     `In an encoding function of the form Encode(dst, src), dst and src were found to reference the same memory`,
We should probably explain _why_ that is an issue. It wouldn't be one if for every byte read we only wrote one byte.

2023-09-21 10:59 UTC, dominikh commented on staticcheck/lint.go
> +			_, dstConst := dst.Value.Value.(*ir.Const)
This will need to use irutil.Flatten on the two values, to account for sigma nodes.

2023-09-21 10:59 UTC, dominikh commented on staticcheck/lint.go
> +	return func(call *Call) {
We have multiple places that check for and ignore `nil`. It'd probably make sense to check if either src or dst are nil and return early.

2023-09-21 10:59 UTC, dominikh commented on staticcheck/lint.go
> +				if dstSlice.X != srcSlice.X {
This needs to handle sigma nodes (via ir.Flatten). Consider this:

```
func foo(a *[4]byte) {
	x := a[:]

	if true {
		y := a[:]
		hex.Encode(x, y)
	}
}
```

2023-09-21 10:59 UTC, dominikh commented on staticcheck/lint.go
> +				if dstSlice.Low == srcSlice.Low {
This needs to handle sigma nodes. Consider this:

```
func foo(a *[4]byte) {
	low := 2
	x := a[low:]

	if true {
		y := a[low:]
		hex.Encode(x, y)
	}
}
```

2023-11-02 21:33 UTC, dominikh requested changes

2023-11-02 21:33 UTC, dominikh commented on staticcheck/lint.go
> +		if !ok {
For the future (because it's not applicable here once you fix the panics): you could drop the `, ok` and just let Go panic on the type assertion.

2023-11-02 21:33 UTC, dominikh commented on staticcheck/lint.go
> +		dstSlice, ok := irutil.Flatten(dst.Value.Value).(*ir.Slice)
`ir.Slice` is the IR instruction for slicing. Not all slices come into existence by something being sliced. For example, analyzing this code panics:

```
func foo(a, b []byte) {
	hex.Encode(a, b)
}
```

As does

```
func foo(n int) {
	a := make([]byte, n)
	b := make([]byte, n)
	hex.Encode(a, b)
}
```

2023-11-02 21:33 UTC, dominikh commented on website/data/checks.json
> +			"TextMarkdown": "In an encoding function of the form Encode(dst, src), dst and src were found to reference the same memory",
This seems to be out of date with the documentation changes you've made.

2023-11-02 21:33 UTC, dominikh commented on staticcheck/doc.go
> +		Text:     `In an encoding function of the form Encode(dst, src), dst and src were found to reference the same memory. This can result in src bytes being overwritten before they are read, when the e
You can use `\'` (backslash followed by single quotation mark) to mark text as code. We translate them to backticks for Markdown.

2023-11-05 23:09 UTC, dominikh approved these changes
I'll take care of the final touch-ups on my end.

2023-11-05 23:09 UTC, dominikh commented on staticcheck/testdata/src/example.com/CheckEncodingAscii85/CheckEncodingAscii85.go
> +	log.Println(ascii85.Encode(sliceA, sliceB))
We don't have to use the results of the Encode functions for these tests.

2023-11-05 23:09 UTC, dominikh commented on staticcheck/doc.go
> +		Severity: lint.SeverityError,
I think this should be a warning, not an error, because the code doesn't panic or return an error.

2023-11-05 23:09 UTC, dominikh commented on staticcheck/doc.go
> +		Text:     `In an encoding function of the form \'Encode(dst, src)\', \'dst\' and \'src\' were found to reference the same memory. This can result in \'src\' bytes being overwritten before they are
The text should be wrapped to 72 characters per line.

2023-11-05 23:34 UTC, closed without merging