staticcheck: new check to flag use of byte slice in io.WriteString
dominikh/go-tools pull request #914
Opened 2021-01-24 15:30 UTC by proishan11

Fixes #839

2021-01-30 04:38 UTC, dominikh requested changes

2021-01-30 04:38 UTC, dominikh commented on staticcheck/doc.go
> +		Since: "2020.2",
2020.2 has already been released and does not include this check. New, unreleased checks should say `Since: "Unreleased"` instead.

2021-01-30 04:38 UTC, dominikh commented on staticcheck/lint.go
> +		if !code.IsCallToAny(pass, call, "io.WriteString") {
Use `code.IsCallTo` instead, since we're only checking for a single name.

2021-01-30 04:38 UTC, dominikh commented on staticcheck/lint.go
> +		if t == nil {
`t` cannot be nil here.

2021-01-30 04:38 UTC, dominikh commented on staticcheck/lint.go
> +			byteArg := conv.Args[0]
The following 6 lines can be simplified to

```
bt, ok := pass.TypesInfo.TypeOf(conv.Args[0]).Underlying().(*types.Slice)
if !ok {
  return
}
```

2021-01-30 04:38 UTC, dominikh commented on staticcheck/testdata/src/CheckByteSliceInIOWriteString/CheckByteSliceInIOWriteString.go
> +package pkg
We should also add tests for the cases that we _don't_ want to flag. WriteString with a string, with a string(b) where b is not a []byte.

We should also add tests for more cases we do want to flag, such as string(b) where b's type is T and `type T []byte`.

2021-05-17 16:28 UTC, proishan11 commented
@dominikh Apologies for the making the changes so late. Please review!

2023-06-23 23:29 UTC, closed without merging